server:
   port: 7500
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/ 
   instance:
      appName:ProductService
spring:
   application:
      name: ProductService
